version: '3.3'

services: 
    mongo:
      image: mongo
      environment: 
        MONGO_INITDB_DATABASE: inspections
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: 123
      ports: 
        - "27017:27017"
  
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 8081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: user
          ME_CONFIG_MONGODB_ADMINPASSWORD: 123
          ME_CONFIG_MONGODB_URL: mongodb://user:123@mongo:27017/
          ME_CONFIG_BASICAUTH: false

    backend:
        build: 
          context: ./backend
          args:
            DB_PORT: 27017
            DB_HOST: 127.0.0.1
            DB_USER: user
            DB_PASS: 123
            DB_NAME: inspections
        depends_on:
          - mongo
        ports:
          - 3000:3000
        environment:
          DB_PORT: 27017
          DB_HOST: mongo
          DB_USER: user
          DB_PASS: 123
          DB_NAME: inspections

    frontend:
        build: ./dot-inspections
        ports:
          - 8000:8000
        environment:
          API_URL: http://backend:3000
